### ISSUE TITLE
Please support current Jackson

### ISSUE THREAD

**Issue by bimargulies** [vznet/mongo-jackson-mapper#10]
with 1.9.4:

java.lang.NoClassDefFoundError: org/codehaus/jackson/map/deser/std/StdDeserializer
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at net.vz.mongodb.jackson.internal.MongoJacksonMapperModule.setupModule(MongoJacksonMapperModule.java:51)
    at org.codehaus.jackson.map.ObjectMapper.registerModule(ObjectMapper.java:444)
    at net.vz.mongodb.jackson.JacksonDBCollection.<clinit>(JacksonDBCollection.java:88)
    at com.basistech.jug.afs.MongoStore.processCorefResult(MongoStore.java:121)
    at com.basistech.jug.afs.MongoStore.writeEntities(MongoStore.java:198)
    at com.basistech.jug.afs.MongoStore.storeResults(MongoStore.java:92)
    at com.basistech.jug.afs.MongoStoreEndpoint.assignTask(MongoStoreEndpoint.java:99)
    at com.basistech.jug.afs.MockDbToMongo.load(MockDbToMongo.java:144)
    at com.basistech.jug.afs.MockDbToMongo.main(MockDbToMongo.java:104)
Caused by: java.lang.ClassNotFoundException: org.codehaus.jackson.map.deser.std.StdDeserializer
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 21 more

**Comment by jroper** [comment]
The current version of mongo-jackson-mapper (1.4.0) was compiled against Jackson 1.9.2.  I upgraded to 1.9.4, and everything still works, and I upgraded to the current version (1.9.5), and it also still works.  The class that isn't found above definitely exists in Jackson 1.9.4:

http://svn.codehaus.org/jackson/tags/1.9/1.9.4/src/mapper/java/org/codehaus/jackson/map/deser/std/StdDeserializer.java

And according to the source code, it is new in 1.9.  So the only way you could have got this error is if you have an older version of Jackson on your classpath.  Please check your classpath carefully.

**Comment by bimargulies** [comment]
Yes, indeed, I mishandled dependency management. Sorry for the noise.

**Comment by jroper** [comment]
No worries, I'm glad you sorted the issue out.
