### ISSUE TITLE
@ObjectId annotated collection methods don't deserialize properly

### ISSUE THREAD

**Issue by brianlenz** [vznet/mongo-jackson-mapper#26]
According to the ObjectId documentation page:

http://vznet.github.com/mongo-jackson-mapper/object-ids.html

You can annotate bean properties with @ObjectId:

```
@ObjectId
public List<String> arbitraryCollectionOfIds;
```

That works just fine.

It also indicates that you can use @ObjectId on getters and setters:

> If using getters and setters, the annotation must be added to both the getter and the setter, for example:

This will also work fine with getters and setters that are a basic type. It will not, however, work if you try this getter/setter approach with a Collection of objects.

Take, for example, the following:

```
private List<String> users;

@ObjectId
public List<String> getUsers() {
    return users;
}

@ObjectId
public void setUsers(List<String> users) {
    this.users = users;
}
```

This will not work. You will run into a ClassCastException like the following:

```
com.mongodb.MongoException$Network: can't call something : brian.home/10.88.0.2:27017/photomento
    at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:227) ~[mongo-java-driver-2.7.2.jar:na]
    at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:305) ~[mongo-java-driver-2.7.2.jar:na]
    at com.mongodb.DBCursor._check(DBCursor.java:369) ~[mongo-java-driver-2.7.2.jar:na]
    at com.mongodb.DBCursor._hasNext(DBCursor.java:498) ~[mongo-java-driver-2.7.2.jar:na]
    at com.mongodb.DBCursor._fill(DBCursor.java:558) ~[mongo-java-driver-2.7.2.jar:na]
    at com.mongodb.DBCursor.toArray(DBCursor.java:596) ~[mongo-java-driver-2.7.2.jar:na]
    at net.vz.mongodb.jackson.DBCursor.toArray(DBCursor.java:383) ~[mongo-jackson-mapper-1.4.2.jar:na]
    at net.vz.mongodb.jackson.DBCursor.toArray(DBCursor.java:370) ~[mongo-jackson-mapper-1.4.2.jar:na]
    ...
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_35]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_35]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_35]
    at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_35]
    at org.restlet.ext.jaxrs.internal.wrappers.AbstractMethodWrapper.internalInvoke(AbstractMethodWrapper.java:171) ~[org.restlet.ext.jaxrs-2.0.13.jar:na]
    at org.restlet.ext.jaxrs.internal.wrappers.ResourceMethod.invoke(ResourceMethod.java:291) ~[org.restlet.ext.jaxrs-2.0.13.jar:na]
    at org.restlet.ext.jaxrs.JaxRsRestlet.invokeMethod(JaxRsRestlet.java:1043) [org.restlet.ext.jaxrs-2.0.13.jar:na]
    at org.restlet.ext.jaxrs.JaxRsRestlet.handle(JaxRsRestlet.java:792) [org.restlet.ext.jaxrs-2.0.13.jar:na]
    at org.restlet.routing.Filter.doHandle(Filter.java:159) [org.restlet-2.0.13.jar:na]
    at org.restlet.routing.Filter.handle(Filter.java:206) [org.restlet-2.0.13.jar:na]
    at org.restlet.routing.Filter.doHandle(Filter.java:159) [org.restlet-2.0.13.jar:na]
    at org.restlet.routing.Filter.handle(Filter.java:206) [org.restlet-2.0.13.jar:na]
    at org.restlet.routing.Filter.doHandle(Filter.java:159) [org.restlet-2.0.13.jar:na]
    at org.restlet.routing.Filter.handle(Filter.java:206) [org.restlet-2.0.13.jar:na]
    at org.restlet.routing.Filter.doHandle(Filter.java:159) [org.restlet-2.0.13.jar:na]
    at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:154) [org.restlet-2.0.13.jar:na]
    at org.restlet.routing.Filter.handle(Filter.java:206) [org.restlet-2.0.13.jar:na]
    at org.restlet.routing.Filter.doHandle(Filter.java:159) [org.restlet-2.0.13.jar:na]
    at org.restlet.routing.Filter.handle(Filter.java:206) [org.restlet-2.0.13.jar:na]
    at org.restlet.engine.ChainHelper.handle(ChainHelper.java:114) [org.restlet-2.0.13.jar:na]
    at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:75) [org.restlet-2.0.13.jar:na]
    at org.restlet.Application.handle(Application.java:391) [org.restlet-2.0.13.jar:na]
    at org.restlet.ext.servlet.ServletAdapter.service(ServletAdapter.java:206) [org.restlet.ext.servlet-2.0.13.jar:na]
    ...
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820) [jetty-runner.jar:7.6.5.v20120716]
    at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:231) [guice-servlet-2.0.1.jar:na]
    at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:142) [guice-servlet-2.0.1.jar:na]
    at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:95) [guice-servlet-2.0.1.jar:na]
    at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:63) [guice-servlet-2.0.1.jar:na]
    at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:122) [guice-servlet-2.0.1.jar:na]
    at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:110) [guice-servlet-2.0.1.jar:na]
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1295) [jetty-runner.jar:7.6.5.v20120716]
    ...
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1295) [jetty-runner.jar:7.6.5.v20120716]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:440) [jetty-runner.jar:7.6.5.v20120716]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131) [jetty-runner.jar:7.6.5.v20120716]
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524) [jetty-runner.jar:7.6.5.v20120716]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225) [jetty-runner.jar:7.6.5.v20120716]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1033) [jetty-runner.jar:7.6.5.v20120716]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:369) [jetty-runner.jar:7.6.5.v20120716]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186) [jetty-runner.jar:7.6.5.v20120716]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:967) [jetty-runner.jar:7.6.5.v20120716]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) [jetty-runner.jar:7.6.5.v20120716]
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:250) [jetty-runner.jar:7.6.5.v20120716]
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:149) [jetty-runner.jar:7.6.5.v20120716]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111) [jetty-runner.jar:7.6.5.v20120716]
    at org.eclipse.jetty.server.Server.handle(Server.java:358) [jetty-runner.jar:7.6.5.v20120716]
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:452) [jetty-runner.jar:7.6.5.v20120716]
    at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:884) [jetty-runner.jar:7.6.5.v20120716]
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:938) [jetty-runner.jar:7.6.5.v20120716]
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:630) [jetty-runner.jar:7.6.5.v20120716]
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230) [jetty-runner.jar:7.6.5.v20120716]
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77) [jetty-runner.jar:7.6.5.v20120716]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:622) [jetty-runner.jar:7.6.5.v20120716]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46) [jetty-runner.jar:7.6.5.v20120716]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603) [jetty-runner.jar:7.6.5.v20120716]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538) [jetty-runner.jar:7.6.5.v20120716]
    at java.lang.Thread.run(Thread.java:680) [na:1.6.0_35]
Caused by: org.codehaus.jackson.map.JsonMappingException: de.undercouch.bson4jackson.types.ObjectId cannot be cast to java.lang.String (through reference chain: xxx.xxx.xxx["users"])
    at org.codehaus.jackson.map.JsonMappingException.wrapWithPath(JsonMappingException.java:218) ~[jackson-mapper-asl-1.9.7.jar:1.9.7]
    at org.codehaus.jackson.map.JsonMappingException.wrapWithPath(JsonMappingException.java:183) ~[jackson-mapper-asl-1.9.7.jar:1.9.7]
    at org.codehaus.jackson.map.deser.BeanDeserializer.wrapAndThrow(BeanDeserializer.java:1472) ~[jackson-mapper-asl-1.9.7.jar:1.9.7]
    at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:699) ~[jackson-mapper-asl-1.9.7.jar:1.9.7]
    at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580) ~[jackson-mapper-asl-1.9.7.jar:1.9.7]
    at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2704) ~[jackson-mapper-asl-1.9.7.jar:1.9.7]
    at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1315) ~[jackson-mapper-asl-1.9.7.jar:1.9.7]
    at net.vz.mongodb.jackson.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:62) ~[mongo-jackson-mapper-1.4.2.jar:na]
    at com.mongodb.Response.<init>(Response.java:66) ~[mongo-java-driver-2.7.2.jar:na]
    at com.mongodb.DBPort.go(DBPort.java:128) ~[mongo-java-driver-2.7.2.jar:na]
    at com.mongodb.DBPort.call(DBPort.java:79) ~[mongo-java-driver-2.7.2.jar:na]
    at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:218) ~[mongo-java-driver-2.7.2.jar:na]
    ... 68 common frames omitted
Caused by: java.lang.ClassCastException: de.undercouch.bson4jackson.types.ObjectId cannot be cast to java.lang.String
    at de.undercouch.bson4jackson.BsonParser.getText(BsonParser.java:613) ~[bson4jackson-1.3.0.jar:na]
    at org.codehaus.jackson.map.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:165) ~[jackson-mapper-asl-1.9.7.jar:1.9.7]
    at org.codehaus.jackson.map.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:146) ~[jackson-mapper-asl-1.9.7.jar:1.9.7]
    at org.codehaus.jackson.map.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:18) ~[jackson-mapper-asl-1.9.7.jar:1.9.7]
    at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299) ~[jackson-mapper-asl-1.9.7.jar:1.9.7]
    at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:414) ~[jackson-mapper-asl-1.9.7.jar:1.9.7]
    at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:697) ~[jackson-mapper-asl-1.9.7.jar:1.9.7]
    ... 76 common frames omitted
```

The issue is caused by a bug in MongoAnnotationIntrospector.findDeserializer() and MongoAnnotationIntrospector.findContentDeserializer(). Both of those methods use am.getGenericType() to determine the type to serialize for. This is fine for all of the annotated types (class, constructor, field, parameter), but it's incorrect for AnnotatedMethod instances.

Since the method is for deserialization, it needs to introspect the setter's first parameter in order to determine the proper deserializer. Instead, since it is using am.getGenericType(), it will always return the "void" type since setters don't return a value. This ultimately prevents a proper deserializer from being determined and causes the ClassCastException.

I have been able to work around the issue by creating my own custom AnnotationIntrospector (via a custom MongoJacksonMapperModule).

The key to the fix is to detect if the Annotated argument is an AnnotatedMethod or not. If it is, then the parameter type needs to be used.

```
private Type getType(Annotated am) {
    if(am instanceof AnnotatedMethod) {
        return ((AnnotatedMethod)am).getParameterType(0);
    }

    return am.getGenericType();
}
```

Then, use getType(am) instead of am.getGenericType() in findDeserializer and findContentDeserializer.

There may be a better solution than this, but I've found that this works for me.

**Comment by bzlat** [comment]
I'm experiencing the same problem, even though I'm annotating the property directly.

I'm testing with the following two very simple models:

User:

<pre><code>
@MongoCollection(name="user")
public class User {
    @Id
    @ObjectId
    public String id;
    @ObjectId
    public List&lt;String&gt; purchaseRefs;
    public static JacksonDBCollection&lt;User, String&gt; coll() {
        return MongoDB.getCollection(User.class, String.class);
    }
    public static List&lt;User&gt; all() {
        User.coll().find().toArray();
    }
}
</code></pre>

Model:

<pre><code>
@MongoCollection(name = "purchase")
public class Purchase extends Model {
    @Id
    @ObjectId
    public String id;
    public double amount;
}
</code></pre>

Invoking the _User.purchases()_ method, leads to the below exception:

<pre><code>
play.core.ActionInvoker$$anonfun$receive$1$$anon$1: Execution exception [[Network: can't call something : /192.168.100.2:27017/mongodbtest]]
    at play.core.ActionInvoker$$anonfun$receive$1.apply(Invoker.scala:134) [play_2.9.1.jar:2.0.4]
    at play.core.ActionInvoker$$anonfun$receive$1.apply(Invoker.scala:115) [play_2.9.1.jar:2.0.4]
    at akka.actor.Actor$class.apply(Actor.scala:318) [akka-actor.jar:2.0.2]
    at play.core.ActionInvoker.apply(Invoker.scala:113) [play_2.9.1.jar:2.0.4]
    at akka.actor.ActorCell.invoke(ActorCell.scala:626) [akka-actor.jar:2.0.2]
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:197) [akka-actor.jar:2.0.2]
Caused by: com.mongodb.MongoException$Network: can't call something : /192.168.100.2:27017/mongodbtest
    at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:227) ~[mongo-java-driver-2.7.2.jar:na]
    at com.mongodb.DBApiLayer$MyCollection.__find(DBApiLayer.java:305) ~[mongo-java-driver-2.7.2.jar:na]
    at com.mongodb.DBCursor._check(DBCursor.java:369) ~[mongo-java-driver-2.7.2.jar:na]
    at com.mongodb.DBCursor._hasNext(DBCursor.java:498) ~[mongo-java-driver-2.7.2.jar:na]
    at com.mongodb.DBCursor._fill(DBCursor.java:558) ~[mongo-java-driver-2.7.2.jar:na]
    at com.mongodb.DBCursor.toArray(DBCursor.java:596) ~[mongo-java-driver-2.7.2.jar:na]
Caused by: org.codehaus.jackson.map.JsonMappingException: de.undercouch.bson4jackson.types.ObjectId cannot be cast to java.lang.String (through reference chain: models.User["purchaseRefs"])
    at org.codehaus.jackson.map.JsonMappingException.wrapWithPath(JsonMappingException.java:218) ~[jackson-mapper-asl.jar:1.9.10]
    at org.codehaus.jackson.map.JsonMappingException.wrapWithPath(JsonMappingException.java:183) ~[jackson-mapper-asl.jar:1.9.10]
    at org.codehaus.jackson.map.deser.BeanDeserializer.wrapAndThrow(BeanDeserializer.java:1472) ~[jackson-mapper-asl.jar:1.9.10]
    at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:699) ~[jackson-mapper-asl.jar:1.9.10]
    at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580) ~[jackson-mapper-asl.jar:1.9.10]
    at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2704) ~[jackson-mapper-asl.jar:1.9.10]
Caused by: java.lang.ClassCastException: de.undercouch.bson4jackson.types.ObjectId cannot be cast to java.lang.String
    at de.undercouch.bson4jackson.BsonParser.getText(BsonParser.java:613) ~[bson4jackson-1.3.0.jar:na]
    at org.codehaus.jackson.map.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:165) ~[jackson-mapper-asl.jar:1.9.10]
    at org.codehaus.jackson.map.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:146) ~[jackson-mapper-asl.jar:1.9.10]
    at org.codehaus.jackson.map.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:18) ~[jackson-mapper-asl.jar:1.9.10]
    at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299) ~[jackson-mapper-asl.jar:1.9.10]
    at org.codehaus.jackson.map.deser.SettableBeanProperty$MethodProperty.deserializeAndSet(SettableBeanProperty.java:414) ~[jackson-mapper-asl.jar:1.9.10]
</code></pre>

Changing this line of code

<pre><code>
@ObjectId
public List&lt;String&gt; purchaseRefs;
</code></pre>

to

<pre><code>
public List&lt;ObjectId&gt; purchaseRefs;
</code></pre>

solves the problem. 

Now I wonder what I'm doing wrong?

**Comment by jroper** [comment]
This project has been moved to:

http://mongojack.org

If this is still an issue, please reraise the issue there.
