### ISSUE TITLE
jackson's byte[] -> base64 serialization breaks

### ISSUE THREAD

**Issue by criedel** [vznet/mongo-jackson-mapper#5]
Hi,
just found out that mongodb isn't able to handle the base64 encoded object that is produced out of byte[] by jackson.
I'd be happy to fix this right now. Could you give me a hint where and what I can do?

Cheers
Christian

**Comment by jroper** [comment]
Firstly write a unit test to reproduce.  There are two different parsers, the stream parser, that uses bson4jackson, and one that converts maps, and the unit tests automatically test both.  If it's not serialising properly, then write a new JsonSerializer, registered in the MongoJacksonSerializers class, that handles byte[], and calls writeObject() on the generator (I think bson4jackson can handle this, but not sure).  If it's not parsing correctly, then you may need to register a new deserialiser for byte[].  I'm also happy to implement this myself, so if you'd rather me do it, just let me know.

**Comment by criedel** [comment]
Ok, have a look at my latest commit. It shows the same error message as our current project. I also found out that it only happens when calling getSavedObject() on the WriteResult. But I wasn't able to fix it myself, I'm still too much newbe in your code :-/

Commit:
https://github.com/CupSoftware/mongo-jackson-mapper/commit/04ead536f6fcd60d80951db55ad8e2764167dc1c

Error:

Tests in error: 
  testSaveAndReturn[stream](net.vz.mongodb.jackson.TestGetSavedObjectWithBinaryData): Don't know how to parse type: class [B

**Comment by criedel** [comment]
In a slightly different situation I'm doing a query on my collection with those binary data.
Some queries work, others don't and throw the following exception:

```
Caused by: java.io.EOFException
    at de.undercouch.bson4jackson.io.LittleEndianInputStream.readFully(LittleEndianInputStream.java:116)
    at de.undercouch.bson4jackson.io.LittleEndianInputStream.readFully(LittleEndianInputStream.java:108)
    at de.undercouch.bson4jackson.BsonParser.handleBinary(BsonParser.java:388)
    at de.undercouch.bson4jackson.BsonParser.nextToken(BsonParser.java:241)
    at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:693)
    at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
    at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2695)
    at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1308)
    at net.vz.mongodb.jackson.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:62)
    at com.mongodb.Response.<init>(Response.java:66)
    at com.mongodb.DBPort.go(DBPort.java:128)
    at com.mongodb.DBPort.call(DBPort.java:79)
    at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:218)
    ... 23 more
```

I'll see if I can write a test for this one, too. What do you think? Are both issues actually the same?

**Comment by jroper** [comment]
I've fixed the initial error, however I don't know what is causing the other issue.  If you could provide a way to reproduce it and raise another issue, that would be great.

**Comment by criedel** [comment]
```
WARNING: emptying DBPortPool to 127.0.0.1:27017 b/c of error
java.io.EOFException
    at de.undercouch.bson4jackson.io.LittleEndianInputStream.readFully(LittleEndianInputStream.java:116)
    at de.undercouch.bson4jackson.io.LittleEndianInputStream.readFully(LittleEndianInputStream.java:108)
    at de.undercouch.bson4jackson.BsonParser.handleBinary(BsonParser.java:388)
    at de.undercouch.bson4jackson.BsonParser.nextToken(BsonParser.java:241)
    at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:693)
    at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
    at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2695)
    at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1308)
    at net.vz.mongodb.jackson.internal.stream.JacksonDBDecoder.decode(JacksonDBDecoder.java:62)
```
